# CITY PARAMETERS
OPENING_HOUR = 9 # @param
CLOSING_HOUR = 18 # @param

# DISEASE PARAMETERS
INCUBATION_DAYS = 14 # @param
NUM_DAYS_SICK = 10 # @param
NUM_WEEKLY_GROCERY_RUNS = 2 # @param

# SIMULATION PARAMETERS
TICK_MINUTE = 2  # @param increment
SIMULATION_DAYS = 30  # @param
SYMPTOM_DAYS = 5  # @param

# LIFESTYLE PARAMETERS
## SHOP
AVERAGE_SHOP_TIME_MINUTES = 30 # @param
SCALE_SHOP_TIME_MINUTES = 15
AVG_SCALE_SHOP_TIME_MINUTES =  10
SCALE_SCALE_SHOP_TIME_MINUTES = 5

## WORK
AVG_WORKING_HOURS = 8
SCALE_WORKING_HOURS = 1
AVG_SCALE_WORKING_HOURS = 2
SCALE_SCALE_WORKING_HOURS = 1

## EXERCISE
AVG_EXERCISE_MINUTES = 60
SCALE_EXERCISE_MINUTES = 15
AVG_SCALE_EXERCISE_MINUTES = 15
SCALE_SCALE_EXERCISE_MINUTES = 5

## MISC
AVG_MISC_MINUTES = 60
SCALE_MISC_MINUTES = 15
AVG_SCALE_MISC_MINUTES = 15
SCALE_SCALE_MISC_MINUTES = 5

WORK_FROM_HOME = False
