#!/bin/bash
TYPE=$1 # "sanity-check"
ACTION=$2 # "plot" or "launch-jobs"
NAME=$3
DEFAULTS=$4

N_PEOPLE=${5:-5000}
INIT=${6:-0.004}

# values
ALL_LEVELS_DROPOUT=(0.02 0.08 0.16 0.32 0.64)
P_DROPOUT_SYMPTOM=(0.20 0.40 0.60 0.80)
PROPORTION_LAB_TEST_PER_DAY=(0.005 0.003 0.0015 0.001 0.0005)
BASELINE_P_ASYMPTOMATIC=(0.5 0.625 0.75 0.875 1.0)
APP_UPTAKE=(0.8415 0.7170 0.5618 0.4215 0.2850)
ASYMPTOMATIC_INFECTION_RATIO=(0.29 0.35 0.40 0.45)

# default index
ALL_LEVELS_DROPOUT_DEFAULT_INDEX=0
P_DROPOUT_SYMPTOM_DEFAULT_INDEX=0
PROPORTION_LAB_TEST_PER_DAY_DEFAULT_INDEX=3
BASELINE_P_ASYMPTOMATIC_DEFAULT_INDEX=2
ASYMPTOMATIC_INFECTION_RATIO_DEFAULT_INDEX=0


# change ALL_LEVELS_DROPOUT
if [ "$TYPE" == "sanity-check" ]; then
  Lx=${ALL_LEVELS_DROPOUT[$ALL_LEVELS_DROPOUT_DEFAULT_INDEX]}
  Sx=${P_DROPOUT_SYMPTOM[$P_DROPOUT_SYMPTOM_DEFAULT_INDEX]}
  Ax=${BASELINE_P_ASYMPTOMATIC[$BASELINE_P_ASYMPTOMATIC_DEFAULT_INDEX]}
  Tx=${PROPORTION_LAB_TEST_PER_DAY[$PROPORTION_LAB_TEST_PER_DAY_DEFAULT_INDEX]}
  AIRx=${ASYMPTOMATIC_INFECTION_RATIO[ASYMPTOMATIC_INFECTION_RATIO_DEFAULT_INDEX]}
  FOLDER_NAME=${NAME}/sensitivity_SC
  intervention=transformer

  if [ "$ACTION" == "launch-jobs" ]; then
    # 30% AR
    ./launch_mobility_experiment.sh Main ${APP_UPTAKE[3]} $Ax $Lx $Sx $Tx \
                          $intervention $FOLDER_NAME $TYPE $N_PEOPLE $INIT $AIRx WORLDLY-GALAXY-801-FINETUNED
  fi

  # plot
  if [ "$ACTION" == "plot" ]; then
      sbatch run_plot_sensitivity.sh Main ${APP_UPTAKE[3]} $Ax $Lx $Sx $Tx XX $FOLDER_NAME $NAME $N_PEOPLE $INIT $AIRx
  fi


fi
