# -------------------------------------
# -----  Simulation Fixed Params  -----
# -------------------------------------
n_people: 1000
simulation_days: 30
test_capacity: 0.005
DROPOUT_RATE: 0.02
INTERVENTION_DAY: 5
tune: true
COLD_CONTAGIOUSNESS: 0
P_CAREFUL_PERSON: 0.3
init_percent_sick: 0.002

# ---------------------------------------
# -----  Experimental Fixed Params  -----
# ---------------------------------------
n_search: -1 # figures out the size of cartesian product for you
USE_INFERENCE_SERVER: False
cpus: 4
env_name: covid38
infra: beluga
time: "'02:50:00'"

# -------------------------
# -----  Directories  -----
# -------------------------
base_dir: /scratch/vsch/covid_sims/app_adopation/moar # if outdir is not provided, runs will be stored in base_dir/${tracing_method}
code_loc: /home/vsch/simulator/src/covid19sim/
weights_dir: /scratch/vsch
use_tmpdir: false

# --------------------------------------
# -----  Sampling Parametrization  -----
# --------------------------------------

tracing_method:
  sample: cartesian
  from:
    - no_intervention
    - heuristicv1
    - transformer>MILD-SOUND-646A
    - transformer>DISTINCTIVE-SILENCE-690B
    - oracle>RADIANT-RESONANCE-561
    - binary_digital_tracing_order_1
    - binary_digital_tracing_order_2

APP_UPTAKE:
  sample: cartesian
  from:
    # - 0.0150 # 1%
    # - 0.4215 # 30%
    - 0.5618 # 40%
    - 0.8415 # 60%
    - 0.9831 # 70%
    # - -1     # 100%

seed:
  sample: cartesian
  from:
    - 5000
    - 5001
    - 5002
